var annotated_dup =
[
    [ "Adopt", "class_adopt.html", "class_adopt" ],
    [ "AdoptCtrl", "class_adopt_ctrl.html", "class_adopt_ctrl" ],
    [ "AdoptModel", "class_adopt_model.html", "class_adopt_model" ],
    [ "Animal", "class_animal.html", "class_animal" ],
    [ "AnimalCtrl", "class_animal_ctrl.html", "class_animal_ctrl" ],
    [ "AnimalModel", "class_animal_model.html", "class_animal_model" ],
    [ "ErrorCtrl", "class_error_ctrl.html", "class_error_ctrl" ],
    [ "Event", "class_event.html", "class_event" ],
    [ "EventCtrl", "class_event_ctrl.html", "class_event_ctrl" ],
    [ "EventModel", "class_event_model.html", "class_event_model" ],
    [ "Favorite", "class_favorite.html", "class_favorite" ],
    [ "FavoriteCtrl", "class_favorite_ctrl.html", "class_favorite_ctrl" ],
    [ "FavoriteModel", "class_favorite_model.html", "class_favorite_model" ],
    [ "Log", "class_log.html", "class_log" ],
    [ "LogCtrl", "class_log_ctrl.html", "class_log_ctrl" ],
    [ "logModel", "classlog_model.html", "classlog_model" ],
    [ "MotherCtrl", "class_mother_ctrl.html", "class_mother_ctrl" ],
    [ "MotherEntity", "class_mother_entity.html", "class_mother_entity" ],
    [ "MotherModel", "class_mother_model.html", "class_mother_model" ],
    [ "PageCtrl", "class_page_ctrl.html", "class_page_ctrl" ],
    [ "Refuge", "class_refuge.html", "class_refuge" ],
    [ "RefugeModel", "class_refuge_model.html", "class_refuge_model" ],
    [ "Testify", "class_testify.html", "class_testify" ],
    [ "TestifyCtrl", "class_testify_ctrl.html", "class_testify_ctrl" ],
    [ "TestifyModel", "class_testify_model.html", "class_testify_model" ],
    [ "User", "class_user.html", "class_user" ],
    [ "UserCtrl", "class_user_ctrl.html", "class_user_ctrl" ],
    [ "UserModel", "class_user_model.html", "class_user_model" ]
];